# Generated by Django 6.0 on 2025-12-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Math', 'Math'), ('CS', 'CS'), ('Science', 'Science'), ('Other', 'Other')], default='General', max_length=30),
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
