# Generated by Django 6.0 on 2025-12-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_note_content_note_category_note_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='description',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Math', 'Math'), ('CS', 'CS'), ('Physics', 'Physics'), ('English', 'English'), ('Other', 'Other')], default='General', max_length=30),
        ),
    ]
