# Generated by Django 6.0 on 2025-12-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_description_note_content_alter_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Math', 'Math'), ('CS', 'Computer Science'), ('Physics', 'Physics'), ('Other', 'Other')], default='General', max_length=50),
        ),
    ]
