# Generated by Django 6.0 on 2025-12-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
