# Generated by Django 6.0 on 2025-12-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_due_date_note_start_date_alter_note_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
